- name: Ensure haproxy is installed
  yum:
    name: haproxy
    state: installed
- name: Create HAProxy config
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
