#- hosts: bastion
#  roles:
#  - dns
#  - ntp
#  - tftp
#  - dhcp
#  - storage
#  - nfs
#  - httpd
#  - rsyslog
#  - haproxy
#  - squid
#  - java
#  - nexus
#- hosts: bastion
#  roles:
#  - kvm
- hosts: kvm
  roles:
  - kvm
- hosts: bastion
  environment:
    http_proxy: "http://{{ hostvars['bastion']['ansible_host'] }}:3128"
    no_proxy: ".{{ ocp4_cluster_domain_name }},192.168.0.0/16"
  roles:
  - upi
