- shell: "{{ ocp4_home }}/bin/oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{\"spec\":{\"storage\":{\"emptyDir\":{}}}}' --kubeconfig={{ ocp4_home }}/bare-metal/auth/kubeconfig"
