- name: Install TFTP Server
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - tftp-server
    - tftp
- name: Enable TFTP service on firewalld
  firewalld:
    service: tftp
    permanent: yes
    state: enabled
- name: Create directory for UEFI
  file:
    path: /var/lib/tftpboot/uefi
    mode: '0755'
- name: Copy UEFI SHIM to TFTP Boot
  copy:
    src: /boot/efi/EFI/redhat/shim.efi
    dest: /var/lib/tftpboot/uefi
    remote_src: yes
    mode: '755'
- name: Copy UEFI Grubx to TFTP Boot 
  copy:
    src: /boot/efi/EFI/redhat/grubx64.efi
    dest: /var/lib/tftpboot/uefi
    remote_src: yes
    mode: '755'
- name: Create TFTP image directory
  file:
    path: /var/lib/tftpboot/images/RedHat-CoreOS
    state: directory
    mode: '0755'
- name: Enable and start TFTP service
  systemd:
    name: tftp
    state: started
    enabled: yes
