- name: Install TFTP Server
  yum:
    name:
      - tftp-server
      - tftp
      - xinetd
    state: present
- name: Enable TFTP service on firewalld
  firewalld:
    service: tftp
    permanent: yes
    state: enabled
- name: Create directory for UEFI
  file:
    path: /var/lib/tftpboot/uefi
    state: directory
    mode: '0755'
- name: Create image directory
  file:
    path: /var/lib/tftpboot/images/RHEL-8.1
    state: directory
- name: Copy vmlinuz
  copy:
    src: /boot/vmlinuz-4.18.0-147.el8.x86_64
    dest: /var/lib/tftpboot/images/RHEL-8.1/vmlinuz
- name: Copy initrd
  copy:
    src: /boot/initramfs-4.18.0-147.el8.x86_64.img
    dest: /var/lib/tftpboot/images/RHEL-8.1/initrd.img
- name: Copy UEFI BOOTX64.EFI to TFTP Boot
  copy:
    src: /boot/efi/EFI/BOOT/BOOTX64.EFI
    dest: /var/lib/tftpboot/uefi/BOOTX64.efi
    remote_src: yes
    mode: '755'
- name: Copy UEFI Grubx to TFTP Boot 
  copy:
    src: /boot/efi/EFI/redhat/grubx64.efi
    dest: /var/lib/tftpboot/uefi
    remote_src: yes
    mode: '755'
- name: Create TFTP image directory
  file:
    path: /var/lib/tftpboot/images/RedHat-CoreOS
    state: directory
    mode: '0755'
- name: Enable and start TFTP service
  systemd:
    name: tftp
    state: restarted
    enabled: yes
- name: Enable and start XINETD service
  systemd:
    name: xinetd
    state: restarted
    enabled: yes
