- name: Install NFS Server
  yum:
    name:
      - nfs-utils
      - rpcbind
    state: present
- name: Enable NFS service on firewalld
  firewalld:
    service: nfs
    permanent: yes
    state: enabled
- name: Copy /etc/exports
  template:
    src: nfs-export.j2
    dest: /etc/exports
- name: Enable and start NFS services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - nfs-server
  - rpcbind
- name: Change permission to nobody
  file:
    path: /mnt/container-storage
    owner: nobody
    group: nobody
