- name: Ensure dhcp is installed
  yum:
    name: dhcp
    state: installed
- name: Create DHCP config
  template:
    src: dhcpd.j2
    dest: /etc/dhcp/dhcpd.conf
- name: restart dhcp
  systemd:
    name: dhcpd
    state: restarted
    enabled: yes
