- name: Create a volume group on top of /dev/sdb1 for detached storage
  lvg:
    vg: vg_ds
    pvs: /dev/sdb1
    pesize: 230G
- name: Create a logical volume to consume all remaining space in the volume group
  lvol:
    vg: vg_ds
    lv: lv_ds
    size: +100%FREE
- name: Create XFS
  filesystem:
    dev: /dev/vg_ds/lv_ds
    fstype: xfs
- name:
  file:
    path: /mnt/detached-storage
    state: directory
- name: Mount detached storage
  mount:
    src: /dev/vg_ds/lv_ds
    path: /mnt/detached-storage
    fstype: xfs
    state: mounted
- name: Create a volume group on top of /dev/sda1
  lvg:
    vg: vg_nfs
    pvs: /dev/sda1
    pesize: 470G
- name: Create a logical volume to consume all remaining space in the volume group
  lvol:
    vg: vg_nfs
    lv: lv_nfs
    size: +100%FREE
- name: Create XFS
  filesystem:
    dev: /dev/vg_nfs/lv_nfs
    fstype: xfs
- name:
  file:
    path: /mnt/container-storage
    state: directory
- name: Mount registry storage
  mount:
    src: /dev/mapper/vg_nfs-lv_nfs
    path: /mnt/container-storage
    fstype: xfs
    state: mounted
